### ISSUE TITLE
Visual notifications for when timer is close when timer is up

### ISSUE THREAD

**Issue by americanhanko** [thestrabusiness/mastermind-hub#11]
**Is your feature request related to a problem? Please describe.**
We've previously used the Zoom chat feature to send timely reminders about how much time the person in the hot seat has. It'd be 

**Describe the solution you'd like**
During my time in the hot seat, I'd like to see visual notifications at certain intervals — maybe would be a user preference at a later time.

**Describe alternatives you've considered**
`¯\_(ツ)_/¯ `

**Comment by thestrabusiness** [comment]
We can use browser notifications for this. I played around with this in the console, and it looks pretty straightforward to use. It's something roughly like:

1. Request permission to show notifications with `Notification.requestPermission()`
1. Handle whether or not permission was granted
1. Show notifications at x minute intervals `new Notification("You've got x minutes left")`

You can check out the [MDN web docs ](https://developer.mozilla.org/en-US/docs/Web/API/notification)for more reading.

**Comment by thestrabusiness** [comment]
A first implementation of this was add in f9247f7dcbc56ed40b37ff1290e3bf49bf2dbf4e
