### ISSUE TITLE
Duplicate groups being created for group owners

### ISSUE THREAD

**Issue by americanhanko** [thestrabusiness/mastermind-hub#18]
**Describe the bug**
Started a group, and received an email to join and also an invite.

**To Reproduce**
1. Start a new group
1. Specify my email address (as a member)
1. Receive welcome email
1. Go to Invites page
1. Accept invite

**Expected behavior**
> "You're already a member of this group"
> "Can't join a group you're already a member of"

or...idempotent/nothing happens.

**Screenshots**
![image](https://user-images.githubusercontent.com/8458267/78504275-e0a83400-7720-11ea-96ca-043f840b9d81.png)

**Comment by thestrabusiness** [comment]
It sounds like we shouldn't send emails out to the person creating the group.

We also need validations around group membership: A member can only have a single membership per group.
