### ISSUE TITLE
Better group management for facilitators

### ISSUE THREAD

**Issue by americanhanko** [thestrabusiness/mastermind-hub#35]
**Is your feature request related to a problem? Please describe.**
As a facilitator, I sent an invite to a user. However, the user lost the original email or deleted it, and I cannot re-create a new invite. Similarly, if I want to remove a user from an existing group, I cannot do so.

**Describe the solution you'd like**
When going to "Edit Group," I would like to see a list of users — and if a user I invited has a pending invite, it would show the user hasn't accepted. Similarly, if I wanted to create a new invite, I would expect a new field where I could specify an email address and add a new user to the group.

**Comment by thestrabusiness** [comment]
#37 and #38 tackled this.
